name: Build RP2350 Firmware

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Build Tools and Libusb
      run: |
        brew update
        brew install cmake picotool libusb

    - name: Install ARM Toolchain
      run: |
        mkdir -p $HOME/toolchains
        cd $HOME/toolchains
        curl -Lo arm-toolchain.tar.xz "https://developer.arm.com/-/media/Files/downloads/gnu/15.2.rel1/binrel/arm-gnu-toolchain-15.2.rel1-darwin-arm64-arm-none-eabi.tar.xz"
        tar -xf arm-toolchain.tar.xz
        echo "$HOME/toolchains/arm-gnu-toolchain-15.2.rel1-darwin-arm64-arm-none-eabi/bin" >> $GITHUB_PATH

    - name: Clone and Setup Pico SDK
      run: |
        git clone --recursive https://github.com/raspberrypi/pico-sdk.git $HOME/pico-sdk
        cd $HOME/pico-sdk
        git checkout a1438dff1d38bd9c65dbd693f0e5db4b9ae91779
        git submodule update --init --recursive
        echo "PICO_SDK_PATH=$HOME/pico-sdk" >> $GITHUB_ENV
        
    - name: Build Firmware
      run: |
        PICO_BOARD="waveshare_rp2350_usb_a"
        PICO_TOOLCHAIN_PATH="$HOME/toolchains/arm-gnu-toolchain-15.2.rel1-darwin-arm64-arm-none-eabi"
        cmake -S . -B build \
          -DPICO_BOARD=$PICO_BOARD \
          -DPICO_SDK_PATH=$PICO_SDK_PATH \
          -DPICO_TOOLCHAIN_PATH=$PICO_TOOLCHAIN_PATH
        cmake --build build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rp2350a-firmware
        path: build/
